apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  selector:
    matchLabels:
      name: locust
      role: worker
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      securityContext: {}
      containers:
      - name: locust-worker
        securityContext: {}
        image: "harbor.harbor.svc.service.wpax.intel.com/dev/zzhou/locust-ml:latest"
        command: ["/bin/bash", "/docker-entrypoint.sh"]
        # args: ["--config=/mnt/locust/configs/worker.conf"]
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
          - name: docker-entrypoint
            mountPath: /docker-entrypoint.sh
          - name: src
            mountPath: /mnt/locust/src
          - name: lib
            mountPath: /mnt/locust/lib
          - name: configs
            mountPath: /mnt/locust/configs
          - name: data
            mountPath: /mnt/locust/data
          - name: logs
            mountPath: /mnt/locust/logs
      restartPolicy: Always
      volumes:
        - name: docker-entrypoint
          hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/locust/docker-entrypoint.sh
            type: File
        - name: src
          hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/locust/src
            type: Directory
        - name: lib
          hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/locust/lib
            type: Directory
        - name: configs
          hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/locust/configs
            type: Directory
        - name: data
          hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/locust/data
            type: Directory
        - name: logs
          hostPath:
            path: /mnt/san03RAID1/users/zzhou/Logs/locust
            type: Directory
