apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tf-tastic
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: chzhyang/of-tf-http-tastic:v1
          imagePullPolicy: IfNotPresent