apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s-dev.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: unique-id-service
  name: unique-id-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: unique-id-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s-dev.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: unique-id-service
    spec:
      containers:
        - command:
            - UniqueIdService
          image: harbor.harbor.svc.service.wpax.intel.com/dev/zzhou/social-network-ml-microservices:latest
          name: unique-id-service
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: unique-id-service-hostpath0
            - mountPath: /keys
              name: unique-id-service-hostpath1
      hostname: unique-id-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/config
          name: unique-id-service-hostpath0
        - hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/keys
          name: unique-id-service-hostpath1
status: {}
