apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s-dev.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: url-shorten-mongodb
  name: url-shorten-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: url-shorten-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s-dev.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: url-shorten-mongodb
    spec:
      containers:
        - args:
            - --config
            - /social-network-microservices/config/mongod.conf
          image: harbor.harbor.svc.service.wpax.intel.com/dev/zzhou/mongo:4.4.6
          name: url-shorten-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: url-shorten-mongodb-hostpath0
            - mountPath: /keys
              name: url-shorten-mongodb-hostpath1
      hostname: url-shorten-mongodb
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/config
          name: url-shorten-mongodb-hostpath0
        - hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/keys
          name: url-shorten-mongodb-hostpath1
status: {}
