apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s-dev.yml --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: user-timeline-redis
  name: user-timeline-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-timeline-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s-dev.yml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: user-timeline-redis
    spec:
      containers:
        - args:
            - /social-network-microservices/config/redis.conf
          image: harbor.harbor.svc.service.wpax.intel.com/dev/zzhou/redis:6.2.4
          name: user-timeline-redis
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: user-timeline-redis-hostpath0
            - mountPath: /keys
              name: user-timeline-redis-hostpath1
      hostname: user-timeline-redis
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/config
          name: user-timeline-redis-hostpath0
        - hostPath:
            path: /mnt/san03RAID1/users/zzhou/Benchmarks/deathstarbench-intel/socialNetworkML/keys
          name: user-timeline-redis-hostpath1
status: {}
