apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        # autoscaling.knative.dev/maxScale: "2"
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"
              #lifecycle:
                # postStart:
                  # exec:
                    #command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
              # preStop:
                  # exec:
                    # command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]