apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: media-filter-service
  name: media-filter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-filter-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: media-filter-service
    spec:
      containers:
        - image: 172.16.3.13:5000/social-network-media-filter-service:latest
          name: media-filter-service
          env:
          - name: https_proxy
            value: "http://proxy-dmz.intel.com:912"
          - name: http_proxy
            value: "http://proxy-dmz.intel.com:912"
          args: ["$(https_proxy) $(http_proxy)"]
          ports:
            - containerPort: 9090
          resources: {}
      hostname: media-filter-service
      restartPolicy: Always
status: {}
