apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.controller.type: daemonset
    kompose.service.nodeport.port: "30080"
    kompose.service.type: nodeport
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-thrift
  name: nginx-thrift
spec:
  ports:
    - name: "8080"
      nodePort: 30080
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: nginx-thrift
  type: NodePort
status:
  loadBalancer: {}
