apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: post-storage-service
  name: post-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-storage-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: post-storage-service
    spec:
      containers:
        - command:
            - PostStorageService
          image: 172.16.3.13:5000/social-network-ml-microservices:latest
          name: post-storage-service
          ports:
            - containerPort: 9090
          resources: {}
      hostname: post-storage-service
      restartPolicy: Always
status: {}
