apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-service
  name: social-graph-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: social-graph-service
    spec:
      containers:
        - command:
            - SocialGraphService
          image: 172.16.3.13:5000/social-network-ml-microservices:latest
          name: social-graph-service
          ports:
            - containerPort: 9090
          resources: {}
      hostname: social-graph-service
      restartPolicy: Always
status: {}
