apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s-opt-avx2.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-redis
  name: social-graph-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s-opt-avx2.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: social-graph-redis
    spec:
      containers:
        - args:
            - /social-network-microservices/config/redis.conf
          image: 10.250.18.9:5000/redis:6.2.4
          name: social-graph-redis
          ports:
            - containerPort: 6379
          resources: {}
      hostname: social-graph-redis
      restartPolicy: Always
status: {}
