apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s-opt-avx2.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: text-filter-service
  name: text-filter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: text-filter-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s-opt-avx2.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: text-filter-service
    spec:
      containers:
        - image: 10.250.18.9:5000/social-network-text-filter-service-opt-avx2:latest
          name: text-filter-service
          ports:
            - containerPort: 9090
          resources: {}
      hostname: text-filter-service
      restartPolicy: Always
status: {}
