apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose-k8s-opt-avx2.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: user-timeline-mongodb
  name: user-timeline-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-timeline-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../docker-compose-k8s-opt-avx2.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: user-timeline-mongodb
    spec:
      containers:
        - args:
            - --config
            - /social-network-microservices/config/mongod.conf
          image: 10.250.18.9:5000/mongo:4.4.6
          name: user-timeline-mongodb
          ports:
            - containerPort: 27017
          resources: {}
      hostname: user-timeline-mongodb
      restartPolicy: Always
status: {}
