apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --file ../docker-compose-k8s-opt-avx512.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-service
  name: social-graph-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --file ../docker-compose-k8s-opt-avx512.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: social-graph-service
    spec:
      containers:
      - command:
        - SocialGraphService
        image: ccr-registry.caas.intel.com/cnbench/dsb-social-ml/social-network-ml-microservices:latest
        imagePullPolicy: ""
        name: social-graph-service
        ports:
        - containerPort: 9090
        resources: {}
      hostname: social-graph-service
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
