apiVersion: v1
kind: Pod
metadata:
  name: wrk
spec:
  volumes:
    - name: lua
      hostPath:
        path: /home/yangge/faas-workloads/tf-knative-event-ceph/wrk-cloudevent
  containers:
    - name: runner
      image: 127.0.0.1:5000/wrk:ubuntu
      imagePullPolicy: Always
      volumeMounts:
        - name: lua
          mountPath: /tmp/wrk-cloudevent
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]