apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tf-function-event-perf-warm
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - name: user-container
        image: docker.io/chzhyang/tf-function-knative-event-ceph:perf
        imagePullPolicy: IfNotPresent